Attribute VB_Name = "Module1"
Public fricls As Integer
Public allkbh As Integer
Public kbcout As Integer
Public kbtext As String
Public kbcolr As String
Public fdctime As Integer
Public fdctext As String
Public fdczt As Boolean
Public ksmsmode As Boolean
